### ISSUE TITLE
Nebensache

### ISSUE THREAD

**Issue by Manos1966** [genmad/shellyAPIGen2AndAboveScripts#3]
Wir haben gesagt, es handelt sich hier um eine:
- Dynamische Steuerung 
- bis zu fünf Wechselrichter
- die **an einer Batterie angeschlossenen** sind

Unter diesen Voraussetzungen funktioniert der Skript P E R F E K T 🥂 mit zwei (und bald werde ich mit drei Wechselrichtern testen koennen).

**Rein Informativ jetzt** nur damit die Einschränkungen des Algorithmus klar sind:

Wenn der erste Wechselrichter die vorher definierte Leistung NICHT bringen kann, weil er an Solar-Paneele angeschlossen sind und die Sonne reicht nicht aus.
Dann bleibt der zweite Wechselrichter weiterhin INAKTIV, obwohl er vielleicht etwas mehr liefern haette koennen.
**Ich erwaehne es nur der Vollständigkeitshalber (es muss nicht geaendert werden)**
Deine Steuerung ist fuer Batterie und nicht fuer Leute die jeden denkbaren Unsinn betreiben wollen. 😉 

Ich habe die Reinfolge der Wechselrichter geaendert. Dadurch konnte der erste (jetzt HM1500) aufgrund der Verschattung, nie die volle Leistung bringen, waehrend der zweite (jetzt HM1200) genug Sonne haette um die fehlende Leistung abzudecken.
Waeren beide an die Batterie angeschlossen, waere so eine Situation nie paasiert.

![61](https://github.com/genmad/shellyAPIGen2AndAboveScripts/assets/129660360/0dc887c5-ca35-407d-8ca3-3b05723aedfc)

![62](https://github.com/genmad/shellyAPIGen2AndAboveScripts/assets/129660360/e68562fb-a81c-4b3a-9075-d03649537386)

**Comment by genmad** [comment]
Also ich finde die Bilder etwas verwirrend, da ich nicht verstehe, warum am HM1500 die Leistung/Netz nicht der der rechts angezeigten Leistung entspricht. Machst du da etwas spezielles oder "Unsinn" :)?

Am HM1200 sieht man wie exakt die Limits eingestellt sind und die Summe aus Netz + Inverter genau dem Minimum in der Konfiguration entspricht. Das ist schön zu sehen.

Wenn du den ersten Wechselrichter in der Konfiguration auf z.B. maximal 300W begrenzt und ihn dann im Controller auch auf diesen Wert begrenzt, dann solltest du bei schwankender Sonne schön die Übergänge in der Wechselrichterkaskade auch bei schlechtem Wetter sehen können.

**Comment by Manos1966** [comment]
> Wenn du den ersten Wechselrichter in der Konfiguration auf z.B. maximal 300W begrenzt und ihn dann im Controller auch auf diesen Wert begrenzt, dann solltest du bei schwankender Sonne schön die Übergänge in der Wechselrichterkaskade auch bei schlechtem Wetter sehen können.


Der erste Wechselrichter in der Konfiguration war auf maximal 900W begrenzt und im Controller auch.

> dann solltest du bei schwankender Sonne schön die Übergänge in der Wechselrichterkaskade auch bei schlechtem Wetter sehen können.

Hmmm... dann muss ich suchen was fuer einen Unsinn ich gemacht habe... 🙈 

>da ich nicht verstehe, warum am HM1500 die Leistung/Netz nicht der der rechts angezeigten Leistung entspricht. 

Ich nehme Bild Nr. 62

- Der Haus Verbrauch ist 764Watt
- Der erste Wechselrichter in der Konfiguration war auf maximal 900W begrenzt.
- Er kann aber nicht mehr als 428,4 Watt liefern (Verschattung)
- Dein Algorithmus merkt, dass 260W noch fehlen. 260W sind innerhalb des 900W Max. Bereiches die der Wechselrichter abdecken kann. Also gibt dein Algoritmus vor, dem ersten Wechelrichter hoeher zu fahren.
In Prinzip richtig! **Woher soll dein Algorithmus wissen, ob der Wechselrichter genug Sonne hat, um die maximale eingestellte Leistung zu liefern, oder nicht?**

**Comment by genmad** [comment]
Was mich da etwas stört, ist dass es nicht sauber auf geht die Rechnung:
Aus Bild 62. LM sagt 286W und am WR kommen nur 260W als Anforderung an. Wo sind denn die anderen 26 W hin? Aber wenn du sagst, dass es so passt, dann bin ich erstmal zu frieden.

**Comment by Manos1966** [comment]
Ah, ich verstehe was du meinst. So kannst du es nicht interpretieren, es sind Bilder aufgenommen **während der Leistungsanpassung**. Das ganze System hatte das "Equilibrium" noch nicht gefunden 😃
